name: CI
on:
  push:
    branches:
      - master
jobs:
  nightly:
    name: Nightly Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[REL]')"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Gather Information
        id: info
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.info.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: |
          yarn install
          yarn run dist
      - name: Building
        run: yarn run release
        env:
          BT_TOKEN: ${{ secrets.BT_KEY }}
  stable:
    name: Stable Build
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[REL]')"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Gather Information
        id: info
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.info.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: |
          yarn install
          yarn run dist
      - name: Building
        run: yarn run release
        env:
          BT_TOKEN: ${{ secrets.BT_KEY }}
